
pipeline {
    agent none 
    stages {
        stage("Backend-image") {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }                
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage("Frontend-image") {
            agent {
                docker { image 'node:16-alpine' }                
            }
            steps {
                sh 'node --version'
            }
        }
        stage("Database-image") {
            agent {
                docker { image 'mysql:latest' }
            }
        }
   }
}
