pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
//    tools {
//        maven "maven-tool"
//    }
    stages {
        stage("Building-NodeJS-image") {
            steps{
                sh 'node --version'
            }
        }
    }
}
